version: '3.5'

services:
 app:
  container_name: nest
  image: chani:1.0
  volumes:
   - ../server/nestjs:/home/node
  ports:
   - 3000:3000
   - 9229:9229
  tty: true
  init: true

 db:
  container_name: pg2
  image: postgres:12.4-alpine
  environment:
   - POSTGRES_USER=pg
   - POSTGRES_PASSWORD=pg
   - PGDATA=/var/lib/postgres/data
  volumes:
   - ../server/data:/var/lib/postgres/data
  ports:
   - 5432:5432